//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Core.NFeRetAutorizacao4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", ConfigurationName="NFeRetAutorizacao4.NFeRetAutorizacao4Soap")]
    public interface NFeRetAutorizacao4Soap {
        
        // CODEGEN: Generating message contract since the operation nfeRetAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/nfeRetAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse nfeRetAutorizacaoLote(NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4/nfeRetAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRetAutorizacaoLoteRequest() {
        }
        
        public nfeRetAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRetAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeRetAutorizacaoLoteResponse() {
        }
        
        public nfeRetAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRetAutorizacao4SoapChannel : NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRetAutorizacao4SoapClient : System.ServiceModel.ClientBase<NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap>, NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap {
        
        public NFeRetAutorizacao4SoapClient() {
        }
        
        public NFeRetAutorizacao4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRetAutorizacao4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRetAutorizacao4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap.nfeRetAutorizacaoLote(NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeRetAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest inValue = new NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse retVal = ((NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap)(this)).nfeRetAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap.nfeRetAutorizacaoLoteAsync(NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest request) {
            return base.Channel.nfeRetAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteResponse> nfeRetAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest inValue = new NFe.Core.NFeRetAutorizacao4.nfeRetAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Core.NFeRetAutorizacao4.NFeRetAutorizacao4Soap)(this)).nfeRetAutorizacaoLoteAsync(inValue);
        }
    }
}
