//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Core.NFeInutilizacao4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", ConfigurationName="NFeInutilizacao4.NFeInutilizacao4Soap")]
    public interface NFeInutilizacao4Soap {
        
        // CODEGEN: Generating message contract since the operation nfeInutilizacaoNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4/nfeInutilizacaoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse nfeInutilizacaoNF(NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4/nfeInutilizacaoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse> nfeInutilizacaoNFAsync(NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeInutilizacaoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeInutilizacaoNFRequest() {
        }
        
        public nfeInutilizacaoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeInutilizacaoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeInutilizacaoNFResponse() {
        }
        
        public nfeInutilizacaoNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeInutilizacao4SoapChannel : NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeInutilizacao4SoapClient : System.ServiceModel.ClientBase<NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap>, NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap {
        
        public NFeInutilizacao4SoapClient() {
        }
        
        public NFeInutilizacao4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeInutilizacao4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeInutilizacao4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeInutilizacao4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap.nfeInutilizacaoNF(NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest request) {
            return base.Channel.nfeInutilizacaoNF(request);
        }
        
        public System.Xml.XmlNode nfeInutilizacaoNF(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest inValue = new NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse retVal = ((NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap)(this)).nfeInutilizacaoNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse> NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap.nfeInutilizacaoNFAsync(NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest request) {
            return base.Channel.nfeInutilizacaoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFResponse> nfeInutilizacaoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest inValue = new NFe.Core.NFeInutilizacao4.nfeInutilizacaoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Core.NFeInutilizacao4.NFeInutilizacao4Soap)(this)).nfeInutilizacaoNFAsync(inValue);
        }
    }
}
