//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Core.NfeStatusServico4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", ConfigurationName="NfeStatusServico4.NfeStatusServico4Soap")]
    public interface NfeStatusServico4Soap {
        
        // CODEGEN: Generating message contract since the operation nfeStatusServicoNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse nfeStatusServicoNF(NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4/nfeStatusServicoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeStatusServicoNFRequest() {
        }
        
        public nfeStatusServicoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeStatusServicoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeStatusServicoNFResponse() {
        }
        
        public nfeStatusServicoNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeStatusServico4SoapChannel : NFe.Core.NfeStatusServico4.NfeStatusServico4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeStatusServico4SoapClient : System.ServiceModel.ClientBase<NFe.Core.NfeStatusServico4.NfeStatusServico4Soap>, NFe.Core.NfeStatusServico4.NfeStatusServico4Soap {
        
        public NfeStatusServico4SoapClient() {
        }
        
        public NfeStatusServico4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeStatusServico4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeStatusServico4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeStatusServico4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse NFe.Core.NfeStatusServico4.NfeStatusServico4Soap.nfeStatusServicoNF(NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNF(request);
        }
        
        public System.Xml.XmlNode nfeStatusServicoNF(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest inValue = new NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse retVal = ((NFe.Core.NfeStatusServico4.NfeStatusServico4Soap)(this)).nfeStatusServicoNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse> NFe.Core.NfeStatusServico4.NfeStatusServico4Soap.nfeStatusServicoNFAsync(NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest request) {
            return base.Channel.nfeStatusServicoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Core.NfeStatusServico4.nfeStatusServicoNFResponse> nfeStatusServicoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest inValue = new NFe.Core.NfeStatusServico4.nfeStatusServicoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Core.NfeStatusServico4.NfeStatusServico4Soap)(this)).nfeStatusServicoNFAsync(inValue);
        }
    }
}
