//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Core.NFeAutorizacao4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", ConfigurationName="NFeAutorizacao4.NFeAutorizacao4Soap")]
    public interface NFeAutorizacao4Soap {
        
        // CODEGEN: Generating message contract since the operation nfeAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse nfeAutorizacaoLote(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest request);
        
        // CODEGEN: Generating message contract since the operation nfeAutorizacaoLoteZip is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse nfeAutorizacaoLoteZip(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeAutorizacaoLoteRequest() {
        }
        
        public nfeAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteResponse() {
        }
        
        public nfeAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public string nfeDadosMsgZip;
        
        public nfeAutorizacaoLoteZipRequest() {
        }
        
        public nfeAutorizacaoLoteZipRequest(string nfeDadosMsgZip) {
            this.nfeDadosMsgZip = nfeDadosMsgZip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteZipResponse() {
        }
        
        public nfeAutorizacaoLoteZipResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeAutorizacao4SoapChannel : NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeAutorizacao4SoapClient : System.ServiceModel.ClientBase<NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap>, NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap {
        
        public NFeAutorizacao4SoapClient() {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap.nfeAutorizacaoLote(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest inValue = new NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse retVal = ((NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse> NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap.nfeAutorizacaoLoteAsync(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest inValue = new NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap.nfeAutorizacaoLoteZip(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZip(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLoteZip(string nfeDadosMsgZip) {
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest inValue = new NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse retVal = ((NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteZip(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap.nfeAutorizacaoLoteZipAsync(NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(string nfeDadosMsgZip) {
            NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest inValue = new NFe.Core.NFeAutorizacao4.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            return ((NFe.Core.NFeAutorizacao4.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteZipAsync(inValue);
        }
    }
}
